baseURL = "https://example.com/"
languageCode = "en-us"
title = "Guy Blachar"
theme = "personal-web"
copyright="©Based on a template by Edna West"
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Guy Blachar"
  sub = "PhD student at Bar-Ilan University"

[params.main]
  latestPublishHeader = ""

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  #mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404
  rendererSafe = false # set to true if wish to remove the unsafe renderer setting below (recommended). Titles will not be run through markdownify

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Page not found!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/guy-blachar.jpg"
[params.assets]
  favicon = ""
  customCSS = ""


[params.contact]
  email = "guy.blachar@gmail.com"
  text= "Email" # text of the contact link in the sidebar. If email params.contact.email is defined
  scholar = "https://scholar.google.com/citations?user=b-LbrlEAAAAJ&hl=en"
  scholartext = "Google Scholar"

#[params.social]
#  googlescholar = "https://scholar.google.com/citations?user=b-LbrlEAAAAJ&hl=en"
#  gmail = "guy.blachar@gmail.com"


[menu]

[[menu.main]]
  identifier = "homepage"
  name = "Homepage"
  title = "Homepage"
  url = "/"
  weight = -120

[[menu.main]]
  identifier = "teaching"
  name = "Teaching"
  title = "Teaching"
  url = "/teaching/"
  weight = -110

#[[menu.main]]
#  identifier = "portfolio"
#  name = "Portfolio"
#  title = "Portfolio"
#  url = "/portfolio/"
#  weight = -110

#[[menu.main]]
#  identifier = "blog"
#  name = "Post"
#  title = "Blog section"
#  url = "/post/"
#  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
